### ISSUE TITLE
problem with installing

### ISSUE THREAD

**Issue by odwamne** [mpaterakis/PlayniteXboxGameBarWidget#1]
hi i was looking on the web for a playnite widget for windows game bar and stumbled on your project i don't know anything about coding but i tried installing this but this error pops up
![Administrator_  Playnite XboxGameBar Widget Installer 08_01_2021 16_44_17](https://user-images.githubusercontent.com/77162569/104034639-72256480-51d1-11eb-97bc-d5002cdd381b.png)

maybe i did something wrong or maybe i'm stupid but i can't make it work

**Comment by mpaterakis** [comment]
Hey there, it seems you are trying to install it inside the OneDrive dir and more specifically Desktop? Try a local directory instead that is **not** a user directory (Desktop, Documents etc), for example `C:\MyApps\XboxWidget`.

**Comment by odwamne** [comment]
hi thanks for the super fast answer i tried that but the same error appears
![Administrator_  Playnite XboxGameBar Widget Installer 08_01_2021 17_45_44](https://user-images.githubusercontent.com/77162569/104041745-c896a100-51d9-11eb-8572-7ec675dbbbf6.png)

**Comment by odwamne** [comment]
hi thanks for the super fast answer i tried that but the same error showes up
![Administrator_  Playnite XboxGameBar Widget Installer 08_01_2021 17_45_44](https://user-images.githubusercontent.com/77162569/104042225-7dc95900-51da-11eb-936d-b9bbef623bb0.png)

**Comment by mpaterakis** [comment]
Oh, I missed a major problem in your first post. You are trying to run the source code without compiling it! You need to download the precompiled binaries from the `Releases` section!
Here's a link: https://github.com/mpaterakis/PlayniteXboxGameBarWidget/releases

EDIT: Updated the README accordingly

**Comment by odwamne** [comment]
thanks a whole lot it works perfectly this was exactly what i was looking for.
thanks for making this and for taking your time to help me install

**Comment by mpaterakis** [comment]
Glad you got it working! Happy gaming!
